plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.14'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.clip'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()

}


dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
	testImplementation "org.testcontainers:mysql"
	testImplementation "org.testcontainers:junit-jupiter"

	testRuntimeOnly 'com.h2database:h2'

	// 도커로 DB를 띄워줄 핵심 라이브러리
	testImplementation "org.testcontainers:junit-jupiter:1.19.0"
	testImplementation "org.testcontainers:mysql:1.19.0"
	// Swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6'

	// OpenNLP
	implementation 'org.apache.opennlp:opennlp-tools:2.3.0'

	implementation 'org.springframework.boot:spring-boot-starter-json'

	// Spring Cloud AWS Starter Secrets Manager
	implementation 'io.awspring.cloud:spring-cloud-aws-starter-secrets-manager:3.1.1'
	implementation 'io.awspring.cloud:spring-cloud-aws-starter:3.1.1'

	// 날짜/시간 타입을 JSON으로 변환
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

	// Spring Security
	implementation 'org.springframework.boot:spring-boot-starter-security'

	// 구글 ID Token 검증
	implementation 'com.google.api-client:google-api-client:2.2.0'

	// JWT (자체 토큰 발급/검증)
	implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'

	// Redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-cache'

	// WebSocket
	implementation 'org.springframework.boot:spring-boot-starter-websocket'

	// Azure Speech SDK (로컬 JAR)
	implementation files('libs/client-sdk-1.40.0.jar')

	//  AWS S3 SDK v2
	implementation platform('software.amazon.awssdk:bom:2.25.0')
	implementation 'software.amazon.awssdk:s3'
	implementation 'software.amazon.awssdk:auth'
	implementation 'software.amazon.awssdk:sso'        // SSO 지원
	implementation 'software.amazon.awssdk:ssooidc'    // SSO 지원
}


tasks.named('test') {
	useJUnitPlatform()
}
