spring:
  config:
    import:
      - "aws-secretsmanager:CLIP/spring-app/dev/env"
      - "aws-secretsmanager:CLIP/spring-app/ExternalAPIs"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${username}
    password: ${password}

  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}
      password: ${spring.data.redis.password}
      ssl:
        enabled: ${spring.data.redis.ssl.enabled}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        instance-profile: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
cors:
  allowed-origins:
    - "chrome-extension://nodoegcapbckibocgdleinfoniaboejg"
    - "chrome-extension://hbhkcidgpjdniofchhofhekjfdcdkkde"
    - "chrome-extension://hchkjnbfbmfgfidilneahojmiddkdeaj"
    - "chrome-extension://eaodakmjolhkaoaofnkfbcodihnncmkn"
    - "chrome-extension://hldepbmgooakmbnbobafccbngfflhilj"
    - "chrome-extension://fiikffmgckeladckjjoalgbeljanpbal"
    - "chrome-extension://mcgnjdjgakffdoagkocfgemnmlndplai"
    - "https://*.youtube.com"
    - "https://dev.clip-server.com"

openai:
  api:
    key: ${openai.api.key}
    url: https://api.openai.com/v1/chat/completions
    model: gpt-5.4-mini

deepl:
  api:
    key: ${deepl.api.key}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000      # 1시간 (Access Token)
  refresh-expiration: 1209600000 # 14일 (Refresh Token)

google:
  client-id: ${google.client-id}

youtube:
  api:
    key: ${YOUTUBE_API_KEY}
    base-url: https://www.googleapis.com/youtube/v3

admin:
  api-key: ${ADMIN_API_KEY}

azure:
  speech:
    key: ${AZURE_SPEECH_KEY}
    region: koreacentral
    language: en-US
    voice-name-female: en-US-JennyNeural
    voice-name-male: en-US-GuyNeural

