spring:
  config:
    import: "aws-secretsmanager:MVP/spring-app/env"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        instance-profile: true

openai:
  api:
    key: ${openai.api.key}
    url: https://api.openai.com/v1/chat/completions
  model: gpt-5.4-mini