spring:
  config:
    import: "aws-secretsmanager:MVP/spring-app/env"
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        instance-profile: true
