name: Java CD with CodeDeploy for Production Environment

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  CODE_DEPLOY_APP_NAME: CLIP-CodeDeploy-App

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./backend/clip-server

    steps:
      - uses: actions/checkout@v4

      - name: Set deployment variables
        run: |
          export TZ='Asia/Seoul'
          echo "DEPLOY_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
          echo "STAGE=prod" >> $GITHUB_ENV
          echo "DEPLOY_GROUP_NAME=CLIP-prod-Group" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Copy Prod Infra Files
        run: |
          cp -r ../../infra/prod/* .

      - name: ZIP deployment package
        run: |
          chmod +x scripts/*.sh
          zip -r clip-${{ env.STAGE }}-deploy-${{ env.DEPLOY_DATE }}.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} clip-${{ env.STAGE }}-deploy-${{ env.DEPLOY_DATE }}.zip s3://${{ secrets.S3_DEPLOY_BUCKET_NAME }}/${{ env.STAGE }}/clip-${{ env.STAGE }}-deploy-${{ env.DEPLOY_DATE }}.zip

      - name: CodeDeploy
        run: |
          aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APP_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.DEPLOY_GROUP_NAME }} \
          --s3-location bucket=${{ secrets.S3_DEPLOY_BUCKET_NAME }},bundleType=zip,key=${{ env.STAGE }}/clip-${{ env.STAGE }}-deploy-${{ env.DEPLOY_DATE }}.zip
