name: Java CD with CodeDeploy for Production Environment

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths:
      - 'backend/clip-server/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ECR_REPOSITORY: clipzy-server-prod
  ECS_CLUSTER: clipzy-server-prod-cluster
  ECS_SERVICE: clipzy-server-prod-service
  ECS_TASK_FAMILY: clipzy-server-prod-task
  CONTAINER_NAME: spring-app

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./backend/clip-server

    steps:
      - uses: actions/checkout@v4

      - name: Set deployment time variable
        run: |
          export TZ='Asia/Seoul'
          echo "DEPLOY_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.DEPLOY_DATE }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download Active Task Definition from AWS ECS
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.ECS_TASK_FAMILY }} \
            --query taskDefinition > task-definition.json

      - name: Render New Image ID in ECS Task Definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Modified Task Definition to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
